import type { Metadata } from 'next'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'IGL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Toaster position='top-right' />
      </body>
    </html>
  )
}
