import type { Metadata } from 'next'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'
import { Toaster } from 'react-hot-toast'
import { UserProvider } from './context/context'

export const metadata: Metadata = {
  title: 'IGL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="favicon.ico" />
        </head>
        <body>
          <Navbar />
          {children}
          <Toaster position='top-right' />
        </body>
      </html>
    </UserProvider>
  )
}
